### ISSUE TITLE
mcmmo no-experience broken.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-3#206]
Using this option:
```
mcmmo:
  no-experience:
    enabled: true
    blacklist:
    - ''
```
mcmmo experience is still given.
Using latest stackmob as of this issue post. Built on: https://github.com/Nathat23/StackMob-3/commit/b2f9a157ab44ecad5793d16586373a7296f02b9b
Using mcmmo classic: https://github.com/mcMMO-Dev/mcMMO-Classic/commits/master
