### ISSUE TITLE
Mob stack limiter

### ISSUE THREAD

**Issue by successed** [Nathat23/StackMob-3#220]
how to If there are 25 sheep in a chunk, stack over 25 pieces.

**Comment by BoozleDoof** [comment]
From within StackMob's configuration file change the **stack-max:** value to however large you wish the maximum stack size to be.

If you want ONLY sheep to stack higher, in the **custom:** section add the following

```
custom:
  SHEEP:
    stack-max: <Maximum Stack Size You Want>
    tag:
      format: '%size%x Sheep'
      always-visible: true
      remove-at: 1
```

**Comment by successed** [comment]
> From within StackMob's configuration file change the **stack-max:** value to however large you wish the maximum stack size to be.
> 
> If you want ONLY sheep to stack higher, in the **custom:** section add the following
> 
> ```
> custom:
>   SHEEP:
>     stack-max: <Maximum Stack Size You Want>
>     tag:
>       format: '%size%x Sheep'
>       always-visible: true
>       remove-at: 1
> ```

I want to do it separately for each creature. for example, I want the chicken to stack when there are 10 in 1 chunk.

**Comment by BoozleDoof** [comment]
```
custom:
  CHICKEN:
    stack-max: 10
    tag:
      format: '%size%x Chicken'
      always-visible: true
      remove-at: 1
```
Add this to the `Custom` section of your configuration.
It will allow chickens to stack up until 10 before starting a new stack.
If you wish to customize more entities, copy the above and paste it below that first one.
Change the entity name to the new entity and the `stack-max:` to your specific needs.

Here's mine as an example, I use it for farm animals.
```
custom:
  SHEEP:
    stack-max: 10
    tag:
      format: '&9%size%x &fSheep'
      always-visible: true
      remove-at: 1
  COW:
    stack-max: 32
    tag:
      format: '&9%size%x &fCow'
      always-visible: true
      remove-at: 1
  PIG:
    stack-max: 32
    tag:
      format: '&9%size%x &fPig'
      always-visible: true
      remove-at: 1
  RABBIT:
    stack-max: 32
    tag:
      format: '&9%size%x &fRabbit'
      always-visible: true
      remove-at: 1
  MUSHROOM_COW:
    stack-max: 16
    tag:
      format: '&9%size%x &fMooshroom'
      always-visible: true
      remove-at: 1
  CHICKEN:
    stack-max: 32
    tag:
      format: '&9%size%x &fChicken'
      always-visible: true
      remove-at: 1
```

Hope that helps. :)
