### ISSUE TITLE
NoSuchMethodError on 1.14.2 Paper

### ISSUE THREAD

**Issue by breadbyte** [Nathat23/StackMob-3#236]
**Describe the bug**
NoSuchMethodError when trying to run on 1.14.2 Paper

**To Reproduce**
Run StackMob v4.0.0 on Paper Build 65

**Expected behavior**
The plugin is enabled.

**Screenshots/Videos**
Here's a gist of the errors.
https://gist.github.com/breadbyte/5923d6287f29b0a52f166b61c56d1ebc

**Bukkit/Spigot AND StackMob version:**
Paper [Paper version git-Paper-65 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
StackMob v4.0.0

**Additional context**
I am running on Java 11 [OpenJDK 64-Bit Server VM (build 11.0.3+7-Debian-1bpo92, mixed mode, sharing)]
I have tested it on Spigot [git-Spigot-baafee9-043d31d (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT] and it works fine.

**Comment by breadbyte** [comment]
I retested this on a blank copy of Paper 65 and it works fine, seems to be a problem with my configuration.

**Comment by HeyZeer0** [comment]
Same problem here, @breadbyte did you figured out how to fix it?

**Comment by Aurelien30000** [comment]
I suggest you to delete your configuration file to reset it, it worked for me ^^

**Comment by HeyZeer0** [comment]
@Aurelien30000 well it actually didn't generated any config files at all, but I tried to delete the folder and the same problem happened :/

**Comment by Aurelien30000** [comment]
I made a PR which should fix this issue (tested in 1.13.2) ;)

**Comment by breadbyte** [comment]
I forgot to mention that yes, it does not generate any configuration files at all.
It only generated general-lang.yml in my case.
<details>
<summary> general-lang.yml </summary>

```

# General translations file for StackMob 3.x
# Minecraft color codes can be used by using the '&' symbol before the letter/number.

# The display information for the 'stick of stacking' which can be obtained with the command '/sm stick'.
stack-tool:
  name: '&6The Stick Of Stacking'
  lore:
  - '&eRight-click an entity to perform selected mode.'
  - '&eShift + right-click an entity to change current mode.'
  - '&bAvailable modes:'
  - '&dSTACK_ONE &7-&a Stack one entity.'
  - '&dSTACK_NEARBY &7-&a Stack all entities in the chunk.'
  - '&dUNSTACK_ONE &7-&a Removes the stack data from one entity'
  - '&dUNSTACK_NEARBY &7-&a Removes the stack data from all entities in the chunk.'
  - '&dSPLIT_ONE &7-&a Splits the stack into two stacks and removes the data from the smallest.'
  - '&dDATA &7-&a Shows basic information about a stack.'
```


</details>

I am currently unable to build your fork, awaiting PR.
