### ISSUE TITLE
Natural

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-3#257]
**Describe the bug**
Naturally generated mobs seem to stack regardless of config options.

**To Reproduce**
I flew around and saw naturally generated mobs start to stack.
Using these config settings relating to generation
```yaml
stack-reasons:
- BREEDING
- SPAWNER
stack-types:
- null
stack-worlds:
- world
- world_the_end
- world_nether
no-stack-reasons:
- BUILD_IRONGOLEM
- BUILD_SNOWMAN
- BUILD_WITHER
- CHUNK_GEN
- CURED
- DEFAULT
- DISPENSE_EGG
- DROWNED
- EGG
- ENDER_PEARL
- INFECTION
- JOCKEY
- LIGHTNING
- MOUNT
- NATURAL
- NETHER_PORTAL
- OCELOT_BABY
- REINFORCEMENTS
- SHEARED
- SHOULDER_ENTITY
- SILVERFISH_BLOCK
- SLIME_SPLIT
- SPAWNER_EGG
- TRAP
- VILLAGE_DEFENSE
- VILLAGE_INVASION
no-stack-types:
- VILLAGER
- PARROT
- HORSE
- OCELOT
- WOLF
- DONKEY
- LLAMA
- ZOMBIE_VILLAGER
- ZOMBIE_HORSE
- SKELETON_HORSE
- SNOWMAN
- TURTLE
- TRIDENT
```

**Expected behavior**
Naturally generated mobs shouldn't stack

**Bukkit/Spigot AND StackMob version:**
Paper 1.13.2 build 637
StackMob 4.0.2
